### ISSUE TITLE
Bootstrap docs

### ISSUE THREAD

**Issue by cpursley** [franklovecchio/running.budget#1]
This looks like a great project. Could you add documentation on how to install and boot it up?

**Comment by franklovecchio** [comment]
Thanks! Waiting on confirmation to contribute again. I do have some docs in the works, hopefully soon!

**Comment by cpursley** [comment]
If you can share the quick tl;dr version here, I don't mind organizing and putting in a PR.

**Comment by franklovecchio** [comment]
I'll get to the setup tonight!

**Comment by franklovecchio** [comment]
Docs are updated for bootstrapping!
